version: '3.9'

services:
  worker:
    image: protokit-executable
    build:
      dockerfile: ./packages/deployment/docker/base/Dockerfile
      context: ../../../..
    container_name: protokit-worker
    environment:
      - LOGGING-LEVEL=${LOGGING_LEVEL:-INFO}
    profiles:
      - worker
    depends_on:
      - sequencer
    networks:
      - db-net
    command: ["${INDEX_JS}", "${PROTOKIT_ENV}", "${WORKER_CONFIG}"]
